import { Vehicle, Driver, FuelTransaction } from '@/types/fuel';

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-001',
    plate: 'BRA-2E19',
    model: 'Gol 1.0 Flex',
    brand: 'Volkswagen',
    year: 2023,
    fuelType: 'flex',
    tankCapacityLiters: 55,
    currentOdometerKm: 48250,
    avgKmPerLiterEstimate: 12.5,
    nfcTagId: 'NFC-TAG-BRA2E19',
    department: 'Vendas & Operacional',
    assignedDriverId: 'drv-001',
    status: 'active',
    notes: 'Veículo da equipe de vendas da Região Metropolitana.'
  },
  {
    id: 'veh-002',
    plate: 'FLT-8890',
    model: 'FH 540 6x4 Heavy Truck',
    brand: 'Volvo',
    year: 2024,
    fuelType: 'diesel',
    tankCapacityLiters: 450,
    currentOdometerKm: 134100,
    avgKmPerLiterEstimate: 2.3,
    nfcTagId: 'NFC-TAG-FLT8890',
    department: 'Logística de Carga Pesada',
    assignedDriverId: 'drv-002',
    status: 'active',
    notes: 'Tanque duplo de alta capacidade. Rota SP - RJ.'
  },
  {
    id: 'veh-003',
    plate: 'LOG-4K12',
    model: 'Strada Freedom 1.3',
    brand: 'Fiat',
    year: 2022,
    fuelType: 'flex',
    tankCapacityLiters: 55,
    currentOdometerKm: 72800,
    avgKmPerLiterEstimate: 11.8,
    nfcTagId: 'NFC-TAG-LOG4K12',
    department: 'Entregas Expressas',
    assignedDriverId: 'drv-003',
    status: 'active',
    notes: 'Utilitário leve para entregas urbanas rápidas.'
  },
  {
    id: 'veh-004',
    plate: 'MNT-3301',
    model: 'Hilux CD SRX 4x4',
    brand: 'Toyota',
    year: 2023,
    fuelType: 'diesel',
    tankCapacityLiters: 80,
    currentOdometerKm: 95400,
    avgKmPerLiterEstimate: 9.5,
    nfcTagId: 'NFC-TAG-MNT3301',
    department: 'Manutenção Externa',
    assignedDriverId: 'drv-004',
    status: 'maintenance',
    notes: 'Em revisão periódica na concessionária.'
  },
  {
    id: 'veh-005',
    plate: 'DIR-0001',
    model: 'Corolla Altis Hybrid',
    brand: 'Toyota',
    year: 2025,
    fuelType: 'flex',
    tankCapacityLiters: 43,
    currentOdometerKm: 18300,
    avgKmPerLiterEstimate: 18.2,
    nfcTagId: 'NFC-TAG-DIR0001',
    department: 'Diretoria Executiva',
    assignedDriverId: 'drv-005',
    status: 'active',
    notes: 'Veículo híbrido de uso executivo.'
  }
];

export const INITIAL_DRIVERS: Driver[] = [
  {
    id: 'drv-001',
    name: 'Carlos Eduardo Silva',
    cnh: '04829301928',
    cnhCategory: 'B',
    pin: '1234',
    phone: '(11) 98765-4321',
    status: 'active',
    assignedVehiclePlate: 'BRA-2E19'
  },
  {
    id: 'drv-002',
    name: 'Roberto Alencar (Beto)',
    cnh: '99281039481',
    cnhCategory: 'E',
    pin: '8821',
    phone: '(11) 97123-9988',
    status: 'active',
    assignedVehiclePlate: 'FLT-8890'
  },
  {
    id: 'drv-003',
    name: 'Mariana Fontes',
    cnh: '12938402931',
    cnhCategory: 'B',
    pin: '4321',
    phone: '(19) 99112-3344',
    status: 'active',
    assignedVehiclePlate: 'LOG-4K12'
  },
  {
    id: 'drv-004',
    name: 'Sérgio Mendes',
    cnh: '88291029381',
    cnhCategory: 'D',
    pin: '5500',
    phone: '(11) 96543-2109',
    status: 'active',
    assignedVehiclePlate: 'MNT-3301'
  },
  {
    id: 'drv-005',
    name: 'Dra. Patricia Lima',
    cnh: '33491029382',
    cnhCategory: 'B',
    pin: '9900',
    phone: '(11) 99887-6655',
    status: 'active',
    assignedVehiclePlate: 'DIR-0001'
  }
];

export const INITIAL_TRANSACTIONS: FuelTransaction[] = [
  {
    id: 'tx-001',
    protocolNumber: 'ABS-2026-0042',
    vehicleId: 'veh-001',
    vehiclePlate: 'BRA-2E19',
    vehicleModel: 'Gol 1.0 Flex',
    driverId: 'drv-001',
    driverName: 'Carlos Eduardo Silva',
    timestamp: '2026-07-22T16:30:00.000Z',
    stationName: 'Posto Petrobras - Av. Central',
    pumpNumber: 'Bomba 03',
    attendantName: 'Marcos - Frentista',
    fuelType: 'gasolina',
    liters: 42.5,
    pricePerLiter: 5.89,
    totalValue: 250.32,
    odometerKm: 48250,
    previousOdometerKm: 47715,
    kmDriven: 535,
    calculatedKmPerLiter: 12.59,
    nfcTagUsed: 'NFC-TAG-BRA2E19',
    authenticatedWithPin: true,
    status: 'approved',
    notes: 'Abastecimento de rotina aprovado.'
  },
  {
    id: 'tx-002',
    protocolNumber: 'ABS-2026-0041',
    vehicleId: 'veh-002',
    vehiclePlate: 'FLT-8890',
    vehicleModel: 'FH 540 6x4 Heavy Truck',
    driverId: 'drv-002',
    driverName: 'Roberto Alencar (Beto)',
    timestamp: '2026-07-21T09:15:00.000Z',
    stationName: 'Posto Graal Rodovia dos Bandeirantes',
    pumpNumber: 'Bomba Diesel 01',
    attendantName: 'Fernando - Frentista',
    fuelType: 'diesel',
    liters: 380.0,
    pricePerLiter: 6.15,
    totalValue: 2337.00,
    odometerKm: 134100,
    previousOdometerKm: 133220,
    kmDriven: 880,
    calculatedKmPerLiter: 2.32,
    nfcTagUsed: 'NFC-TAG-FLT8890',
    authenticatedWithPin: true,
    status: 'approved',
    notes: 'Rota longa concluída com sucesso.'
  },
  {
    id: 'tx-003',
    protocolNumber: 'ABS-2026-0040',
    vehicleId: 'veh-003',
    vehiclePlate: 'LOG-4K12',
    vehicleModel: 'Strada Freedom 1.3',
    driverId: 'drv-003',
    driverName: 'Mariana Fontes',
    timestamp: '2026-07-20T18:45:00.000Z',
    stationName: 'Posto Shell - Marginal Pinheiros',
    pumpNumber: 'Bomba 02',
    attendantName: 'Rafaela - Frentista',
    fuelType: 'etanol',
    liters: 48.0,
    pricePerLiter: 3.99,
    totalValue: 191.52,
    odometerKm: 72800,
    previousOdometerKm: 72260,
    kmDriven: 540,
    calculatedKmPerLiter: 11.25,
    nfcTagUsed: 'NFC-TAG-LOG4K12',
    authenticatedWithPin: true,
    status: 'approved',
    notes: 'Tanque cheio com Etanol.'
  },
  {
    id: 'tx-004',
    protocolNumber: 'ABS-2026-0039',
    vehicleId: 'veh-001',
    vehiclePlate: 'BRA-2E19',
    vehicleModel: 'Gol 1.0 Flex',
    driverId: 'drv-001',
    driverName: 'Carlos Eduardo Silva',
    timestamp: '2026-07-18T11:20:00.000Z',
    stationName: 'Posto Ipiranga - Bairro Jardim',
    pumpNumber: 'Bomba 05',
    attendantName: 'Marcos - Frentista',
    fuelType: 'gasolina',
    liters: 58.0, // Alert: exceeds 55L capacity!
    pricePerLiter: 5.85,
    totalValue: 339.30,
    odometerKm: 47715,
    previousOdometerKm: 47400,
    kmDriven: 315,
    calculatedKmPerLiter: 5.43, // Suspiciously low KM/L
    nfcTagUsed: 'NFC-TAG-BRA2E19',
    authenticatedWithPin: true,
    status: 'flagged',
    flags: ['Volume excede capacidade nominal do tanque (55L)', 'Média KM/L (5.4) abaixo da média esperada (12.5)'],
    notes: 'Alerta gerado automaticamente pelo sistema de segurança.'
  }
];
